# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New1208' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New1208
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'NewPopMenu'
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'
  pod 'SnapKit', '~> 5.0.0'


end
